
import 'package:flutter/material.dart';
import 'package:moftah/data/models/onboarding_page_data.dart';

 const onboardingPages = [
    OnboardingPageData(
      badge: 'كل عربيتك في مكان واحد',
      title: 'مفتاح يخلي التعامل\nمع عربيتك أسهل',
      subtitle: 'صيانة، قطع غيار، ورش قريبة ومساعدة على الطريق من تطبيق واحد.',
      heroIcon: Icons.directions_car_filled_rounded,
      smallIcon1: Icons.build_circle_rounded,
      
      smallIcon2: Icons.local_shipping_rounded,
      highlightTitle: 'كل خدماتك في مكان واحد',
      highlightSubtitle: 'متابعة أسرع وقرارات أوضح لعربيتك',
      benefit1Title: 'ورش قريبة',
      benefit1Subtitle: 'حسب موقعك',
      benefit1Icon: Icons.location_on_rounded,
      benefit2Title: 'قطع مناسبة',
      benefit2Subtitle: 'حسب عربيتك',
      benefit2Icon: Icons.settings_rounded,
      benefit3Title: 'متابعة الصيانة',
      benefit3Subtitle: 'كل التفاصيل',
      benefit3Icon: Icons.car_repair_rounded,
    ),
    OnboardingPageData(
      badge: 'مساحة شغل للفني',
      title: 'خبرتك توصل\nلعملاء أكتر',
      subtitle:
          'استقبل طلبات قريبة منك، نظم شغلك وابنِ تقييم قوي يخلي العميل يختارك.',
      heroIcon: Icons.engineering_rounded,
      smallIcon1: Icons.assignment_turned_in_rounded,
      smallIcon2: Icons.star_rounded,
      highlightTitle: 'شغلك أقرب للعملاء',
      highlightSubtitle: 'طلبات مناسبة لمكانك وخبرتك',
      benefit1Title: 'طلبات قريبة',
      benefit1Subtitle: 'حسب المنطقة',
      benefit1Icon: Icons.near_me_rounded,
      benefit2Title: 'تقييم أفضل',
      benefit2Subtitle: 'يبني ثقة',
      benefit2Icon: Icons.star_rounded,
      benefit3Title: 'تنظيم الشغل',
      benefit3Subtitle: 'طلبات ومواعيد',
      benefit3Icon: Icons.event_note_rounded,
    ),
    OnboardingPageData(
      badge: 'إدارة مركز الصيانة',
      title: 'مركزك أقرب\nلعملاء منطقتك',
      subtitle:
          'استقبل الطلبات، تابع المواعيد واعرض خدمات مركزك بصورة احترافية.',
      heroIcon: Icons.storefront_rounded,
      smallIcon1: Icons.calendar_month_rounded,
      smallIcon2: Icons.analytics_rounded,
      highlightTitle: 'مركزك يظهر بشكل احترافي',
      highlightSubtitle: 'إدارة أفضل ووصول لعملاء أكتر',
      benefit1Title: 'طلبات جديدة',
      benefit1Subtitle: 'من منطقتك',
      benefit1Icon: Icons.inbox_rounded,
      benefit2Title: 'إدارة المواعيد',
      benefit2Subtitle: 'بسهولة',
      benefit2Icon: Icons.calendar_month_rounded,
      benefit3Title: 'متابعة الأداء',
      benefit3Subtitle: 'بشكل أوضح',
      benefit3Icon: Icons.analytics_rounded,
    ),
    OnboardingPageData(
      badge: 'خدمات الونش',
      title: 'طلبات الطريق\nتوصلك أسرع',
      subtitle: 'حدد نطاق خدمتك ومحافظتك واستقبل طلبات السائقين المحتاجين ونش.',
      heroIcon: Icons.local_shipping_rounded,
      smallIcon1: Icons.location_on_rounded,
      smallIcon2: Icons.route_rounded,
      highlightTitle: 'قريب من طلبات الطريق',
      highlightSubtitle: 'استقبل الطلبات داخل نطاق خدمتك مباشرة',
      benefit1Title: 'طلبات قريبة',
      benefit1Subtitle: 'داخل منطقتك',
      benefit1Icon: Icons.location_on_rounded,
      benefit2Title: 'نطاق محدد',
      benefit2Subtitle: 'أنت تتحكم فيه',
      benefit2Icon: Icons.radar_rounded,
      benefit3Title: 'تواصل مباشر',
      benefit3Subtitle: 'مع العميل',
      benefit3Icon: Icons.chat_bubble_rounded,
    ),
  ];